version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
  redis:
    image: redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local

