version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'

